# Generated by Django 4.0.4 on 2022-05-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calories',
            options={'verbose_name': 'Калории', 'verbose_name_plural': 'Калории'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeimage',
            options={'verbose_name': 'Фото рецептов', 'verbose_name_plural': 'Фото рецептов'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Виден?'),
        ),
    ]
