# Generated by Django 4.0.4 on 2022-05-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_calories_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories',
            name='carbohydrates',
            field=models.FloatField(verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='calories',
            name='fats',
            field=models.FloatField(verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='calories',
            name='squirrels',
            field=models.FloatField(verbose_name='Белки'),
        ),
    ]
